import Axios from 'axios'

export const http = Axios.create({
  baseURL: 'toolbox/studio/web/admin/v1',
  headers: { 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyMTRiYWMxMmQyYjQ0OWVhZWI3NDg5ZWUyMjIzOTk3Iiwic3ViIjoiNTIxNGJhYzEyZDJiNDQ5ZWFlYjc0ODllZTIyMjM5OTciLCJncm91cElkIjoiMDRlM2IxYmRiMjY5NDRlNzgyOTU3MTFmODZmZTNkOWEiLCJ0ZW5hbnRJZCI6IjA0ZTNiMWJkYjI2OTQ0ZTc4Mjk1NzExZjg2ZmUzZDlhIiwiaWF0IjoxNjM0MDk1NjE2LCJleHAiOjE2MzQ1Mjc2MTYsImF1ZCI6Ind3dy5haXJjbGFzcy50b3AiLCJpc3MiOiJ3d3cuYWlyY2xhc3MudG9wIn0.IJCVU3i-hEQLLxsTZLqL4AScOSDnsbLIE3OuWjT3jrU' }
})
